blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/vit0-9/transcriptd/discussions
    about: Get help, suggest an idea, or ask a question in our community discussions.
